# Generated by Django 4.2.7 on 2026-06-11 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meters', '0002_meterreading_reading_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meterreading',
            options={'ordering': ['-reading_date', '-created_at']},
        ),
    ]
