# Generated by Django 4.2.7 on 2026-07-04 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meters', '0004_meter_barcode_and_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='meter',
            new_name='meters_barcode_f3970e_idx',
            old_name='meters_barcode_idx',
        ),
        migrations.RenameIndex(
            model_name='meterreading',
            new_name='meter_readi_meter_i_eff11d_idx',
            old_name='meterreading_meter_date_idx',
        ),
    ]
