# Generated by Django 4.2.7 on 2026-08-04 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meters', '0005_rename_meters_barcode_idx_meters_barcode_f3970e_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meter',
            name='initial_reading',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Meter's dial reading at assignment time — baseline for this meter's first bill.", max_digits=10),
        ),
    ]
