# Generated by Django 4.2.7 on 2026-07-06 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_package_conversion_factor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='unit_type',
            field=models.CharField(choices=[('m3', 'Cubic Meter (m3)'), ('kg', 'Kilogram (Kg)')], default='m3', max_length=20),
        ),
    ]
