# Generated by Django 4.2.7 on 2026-09-29 12:03

import apps.messaging.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('units', '0001_initial'),
        ('billing', '0004_widen_usage_kg_precision'),
        ('buildings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0003_alter_package_unit_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('kind', models.CharField(choices=[('bill_created', 'Bill created'), ('reminder', 'Payment reminder'), ('notice', 'Notice')], max_length=20)),
                ('body', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_system', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sms_templates',
                'ordering': ['kind', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SMSSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_bill_created', models.BooleanField(default=True)),
                ('auto_reminders', models.BooleanField(default=True)),
                ('reminder_days', models.JSONField(default=apps.messaging.models.default_reminder_days)),
                ('send_hour', models.PositiveSmallIntegerField(default=10)),
                ('remind_months_back', models.PositiveSmallIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sms_settings',
            },
        ),
        migrations.CreateModel(
            name='SMSCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('body', models.TextField()),
                ('audience', models.CharField(choices=[('all', 'All active units'), ('project', 'A project'), ('building', 'A building'), ('units', 'Specific units')], max_length=20)),
                ('unit_ids', models.JSONField(blank=True, default=list)),
                ('only_unpaid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='buildings.building')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='projects.project')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='messaging.smstemplate')),
            ],
            options={
                'db_table': 'sms_campaigns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SMSMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('bill_created', 'Bill created'), ('reminder', 'Payment reminder'), ('notice', 'Notice'), ('test', 'Test')], max_length=20)),
                ('mobile', models.CharField(blank=True, max_length=20)),
                ('body', models.TextField()),
                ('segments', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('Queued', 'Queued'), ('Sent', 'Sent'), ('Failed', 'Failed'), ('Skipped', 'Skipped')], default='Queued', max_length=20)),
                ('error', models.CharField(blank=True, max_length=500)),
                ('provider_response', models.CharField(blank=True, max_length=1000)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('reminder_day', models.PositiveSmallIntegerField(default=0)),
                ('period', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_messages', to='billing.bill')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='messaging.smscampaign')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_messages', to='units.unit')),
            ],
            options={
                'db_table': 'sms_messages',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='sms_message_status_c1cd11_idx'), models.Index(fields=['-created_at'], name='sms_message_created_66bff0_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='smsmessage',
            constraint=models.UniqueConstraint(condition=models.Q(('bill__isnull', False)), fields=('bill', 'kind', 'reminder_day', 'period'), name='uniq_sms_bill_kind_day_period'),
        ),
    ]
