# Generated by Django 4.2.7 on 2026-06-09 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('buildings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_number', models.CharField(max_length=50, unique=True)),
                ('billing_month', models.DateField()),
                ('previous_reading', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('current_reading', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_usage_m3', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_usage_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('conversion_factor', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('base_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('service_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('extra_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('late_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_adjusted', models.BooleanField(default=False)),
                ('adjustment_reason', models.TextField(blank=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('due_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('Unpaid', 'Unpaid'), ('Partial', 'Partial'), ('Paid', 'Paid')], default='Unpaid', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bills', to='buildings.building')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills_created', to=settings.AUTH_USER_MODEL)),
                ('last_updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills_updated', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bills', to='projects.project')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bills', to='units.unit')),
            ],
            options={
                'db_table': 'bills',
                'ordering': ['-billing_month', '-created_at'],
                'unique_together': {('unit', 'billing_month')},
            },
        ),
    ]
