# Generated by Django 4.2.7 on 2026-09-09 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_widen_reading_precision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='total_usage_kg',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
    ]
