# Generated by Django 4.2.7 on 2026-06-11 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffuser',
            name='mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddConstraint(
            model_name='staffuser',
            constraint=models.UniqueConstraint(condition=models.Q(('mobile__isnull', False)), fields=('mobile',), name='unique_staff_mobile_when_exists'),
        ),
    ]
