# Generated by Django 4.2.7 on 2026-06-15 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_staffuser_mobile_and_more'),
        ('authentication', '0002_customeruser_email'),
    ]

    operations = [
    ]
