# Generated by Django 4.2.7 on 2026-06-17 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_merge_20260615_1143'),
        ('authentication', '0003_staffuser_created_by_userpermission'),
    ]

    operations = [
    ]
