# Generated by Django 4.2.7 on 2026-06-17 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_merge_20260617_1624'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='staffuser',
            name='unique_staff_mobile_when_exists',
        ),
        migrations.AlterField(
            model_name='staffuser',
            name='mobile',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
