# Generated by Django 4.2.7 on 2026-07-16 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_remove_staffuser_unique_staff_mobile_when_exists_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpermission',
            name='module',
            field=models.CharField(choices=[('projects', 'Projects'), ('buildings', 'Buildings'), ('units', 'Units'), ('meters', 'Meters'), ('quick_reading', 'Quick Reading'), ('billing', 'Billing'), ('payments', 'Payments'), ('reports', 'Reports'), ('staff', 'Staff Management'), ('audit', 'Audit Logs')], max_length=30),
        ),
    ]
