# Generated by Django 4.2.7 on 2026-08-01 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_userpermission_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpermission',
            name='module',
            field=models.CharField(choices=[('dashboard', 'Dashboard'), ('projects', 'Projects'), ('packages', 'Packages'), ('buildings', 'Buildings'), ('units', 'Units'), ('meters', 'Meters'), ('quick_reading', 'Quick Reading'), ('billing', 'Billing'), ('payments', 'Payments'), ('reports', 'Reports'), ('financial_reports', 'Financial Reports'), ('staff', 'Staff Management'), ('audit', 'Audit Logs')], max_length=30),
        ),
    ]
