# Generated by Django 4.2.7 on 2026-08-02 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_userpermission_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeruser',
            name='password',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
