# Generated by Django 4.2.7 on 2026-07-22 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0006_alter_userpermission_module'),
        ('billing', '0002_alter_bill_last_updated_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('bill_created', 'New Bill'), ('reminder_5', 'Payment Reminder (5th)'), ('reminder_10', 'Payment Reminder (10th)')], max_length=20)),
                ('title', models.CharField(max_length=150)),
                ('message', models.CharField(max_length=300)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='billing.bill')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='authentication.customeruser')),
            ],
            options={
                'db_table': 'portal_notifications',
                'ordering': ['-created_at'],
                'unique_together': {('bill', 'notification_type')},
            },
        ),
    ]
