# Generated by Django 4.2.7 on 2026-06-29 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_approval_status_payment_approved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='proof_image',
            field=models.ImageField(blank=True, null=True, upload_to='payment_proofs/images/'),
        ),
        migrations.AddField(
            model_name='payment',
            name='proof_invoice',
            field=models.FileField(blank=True, null=True, upload_to='payment_proofs/invoices/'),
        ),
    ]
