# Generated by Django 4.2.7 on 2026-06-29 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_proof_image_payment_proof_invoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='approval_status',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='proof_image',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='proof_invoice',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='rejection_reason',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='submitted_by_customer',
        ),
    ]
