# Generated by Django 4.2.7 on 2026-07-05 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_payment_channel_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentchannelsettings',
            name='bkash_type',
            field=models.CharField(blank=True, default='Personal', help_text='e.g. Personal / Merchant', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentchannelsettings',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='paymentchannelsettings',
            name='instructions',
            field=models.TextField(blank=True, help_text='Optional extra note shown to customers'),
        ),
    ]
