# Generated by Django 4.2.7 on 2026-06-09 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('buildings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_no', models.IntegerField()),
                ('unit_no', models.CharField(max_length=10)),
                ('meter_no', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('mobile_number', models.CharField(blank=True, max_length=15, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='buildings.building')),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.package')),
            ],
            options={
                'db_table': 'units',
                'unique_together': {('building', 'floor_no', 'unit_no')},
            },
        ),
        migrations.CreateModel(
            name='Allottee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('nid', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='allottee', to='units.unit')),
            ],
            options={
                'db_table': 'allottees',
            },
        ),
    ]
